version: '3.8'

services:
  redis:
    image: redis:7.2.3-alpine3.18
    container_name: cache_service
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    restart: always
    volumes:
      - instaresume-redis:/data

volumes:
  instaresume-redis:
    driver: local
